---
params:
  project_name: BiB_Breathes
---





# BiB Breathes {#bib_breathes}


```{r echo=FALSE}
dl_types <- c('Table detail', 'Variable detail', 'Variable names')
dl_csvs <- c('
bib_breathes
_tables.csv', '
bib_breathes
_variables_meta.csv', '
bib_breathes
_variables_names.csv')
make_download_table(dl_types, dl_csvs)
```



BiB Breathes survey and associated data



```{r, include=FALSE}
prj_name <- 'BiB_Breathes'
source('../R/get_all_project_metadata.R', local = knitr::knit_global())
```



```{r, include=FALSE}
source('../R/make_project_tables_display.R', local = knitr::knit_global())
```



```{r, echo=FALSE, file='../R/reactable_project_tables.R'}

```





## BREATHES Air quality survey Phase 1 {#bib_breathes_bibbr_phase1}


```{r echo=FALSE}
dl_types <- c('Variable detail', 'Variable names')
dl_csvs <- c('
bib_breathes_bibbr_phase1
_variables_meta.csv', '
bib_breathes_bibbr_phase1
_variables_names.csv')
make_download_table(dl_types, dl_csvs)
```



Air quality survey from the BiB BREATHES study



```{r, include=FALSE}
tab_id <- 'BiB_Breathes.BiBBr_Phase1'
prj_name <- 'BiB_Breathes'
source('../R/make_table_info_display.R', local = knitr::knit_global())
```



```{r, echo=FALSE, file='../R/reactable_table_info.R'}

```



```{r, include=FALSE}
source('../R/make_var_info_display.R', local = knitr::knit_global())
```



```{r, echo=FALSE, file='../R/reactable_vars.R'}

```





## BREATHES Air quality survey Phase 2 {#bib_breathes_bibbr_phase2}


```{r echo=FALSE}
dl_types <- c('Variable detail', 'Variable names')
dl_csvs <- c('
bib_breathes_bibbr_phase2
_variables_meta.csv', '
bib_breathes_bibbr_phase2
_variables_names.csv')
make_download_table(dl_types, dl_csvs)
```



Air quality survey from the BiB BREATHES study



```{r, include=FALSE}
tab_id <- 'BiB_Breathes.BiBBr_Phase2'
prj_name <- 'BiB_Breathes'
source('../R/make_table_info_display.R', local = knitr::knit_global())
```



```{r, echo=FALSE, file='../R/reactable_table_info.R'}

```



```{r, include=FALSE}
source('../R/make_var_info_display.R', local = knitr::knit_global())
```



```{r, echo=FALSE, file='../R/reactable_vars.R'}

```



