---
params:
  project_name: BiB_Glycomics
---





# BiB Glycomics {#bib_glycomics}


```{r echo=FALSE}
dl_types <- c('Table detail', 'Variable detail', 'Variable names')
dl_csvs <- c('
bib_glycomics
_tables.csv', '
bib_glycomics
variables_meta.csv', '
bib_glycomics
_variables_names.csv')
make_download_table(dl_types, dl_csvs)
```



Glycomics samples for BiB participants



```{r, include=FALSE}
prj_name <- 'BiB_Glycomics'
source('../R/get_all_project_metadata.R', local = knitr::knit_global())
```



```{r, include=FALSE}
source('../R/make_project_tables_display.R', local = knitr::knit_global())
```



```{r, echo=FALSE, file='../R/reactable_project_tables.R'}

```





## Total plasma glycome analyses using HILIC-UHPLC-FLR method {#bib_glycomics_glycomics}


```{r echo=FALSE}
dl_types <- c('Variable detail', 'Variable names')
dl_csvs <- c('
bib_glycomics_glycomics
_variables_meta.csv', '
bib_glycomics_glycomics
_variables_names.csv')
make_download_table(dl_types, dl_csvs)
```



Total plasma glycome analyses using HILIC-UHPLC-FLR method



```{r, include=FALSE}
tab_id <- 'BiB_Glycomics.glycomics'
prj_name <- 'BiB_Glycomics'
source('../R/make_table_info_display.R', local = knitr::knit_global())
```



```{r, echo=FALSE, file='../R/reactable_table_info.R'}

```



```{r, include=FALSE}
source('../R/make_var_info_display.R', local = knitr::knit_global())
```



```{r, echo=FALSE, file='../R/reactable_vars.R'}

```



