---
params:
  project_name: BiBBS_Baseline
---





# BiBBS Baseline {#bibbs_baseline}


```{r echo=FALSE}
dl_types <- c('Table detail', 'Variable detail', 'Variable names')
dl_csvs <- c('
bibbs_baseline
_tables.csv', '
bibbs_baseline
_variables_meta.csv', '
bibbs_baseline
_variables_names.csv')
make_download_table(dl_types, dl_csvs)
```



Baseline surveys completed on BiBBS cohort registration during pregnancy.



```{r, include=FALSE}
prj_name <- 'BiBBS_Baseline'
source('../R/get_all_project_metadata.R', local = knitr::knit_global())
```



```{r, include=FALSE}
source('../R/make_project_tables_display.R', local = knitr::knit_global())
```



```{r, echo=FALSE, file='../R/reactable_project_tables.R'}

```





## Mother baseline pregnancy survey {#bibbs_baseline_pregnancy_survey}


```{r echo=FALSE}
dl_types <- c('Variable detail', 'Variable names')
dl_csvs <- c('
bibbs_baseline_pregnancy_survey
_variables_meta.csv', '
bibbs_baseline_pregnancy_survey
_variables_names.csv')
make_download_table(dl_types, dl_csvs)
```



Maternal baseline pregnancy survey. Harmonised data across all survey versions up to the 2019-11-30 datafreeze.



```{r, include=FALSE}
tab_id <- 'BiBBS_Baseline.pregnancy_survey'
prj_name <- 'BiBBS_Baseline'
source('../R/make_table_info_display.R', local = knitr::knit_global())
```



```{r, echo=FALSE, file='../R/reactable_table_info.R'}

```



```{r, include=FALSE}
source('../R/make_var_info_display.R', local = knitr::knit_global())
```



```{r, echo=FALSE, file='../R/reactable_vars.R'}

```



