---
title: BiB Data Dictionary <span class='dev-version'>Development Version</span>
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE}

library(epivaultr)
library(dplyr)
library(knitr)
library(reactable)
library(V8)
library(here)
library(htmltools)
library(stringr)
library(ggplot2)
library(tidyr)

source("../R/setup/datadict-functions.R")

csv_dir <- "../docs/csv/"

csv_link_dir <- "csv/"

options(ev_server = "BHTS-RESRCH22DV")
options(ev_database = "ResearchWarehouse")

con <- ev_connect()

projects <- ev_simple_fetch(con, "DataDictionary", "metadata_project")
tables <- ev_simple_fetch(con, "DataDictionary", "metadata_table")

terms_closer <- ev_simple_fetch(con, "DataDictionary", "terms_closer")
terms_bib <- ev_simple_fetch(con, "DataDictionary", "terms_bib")


terms_closer <- terms_closer |> select(closer_term = name,
                                       closer_title = title,
                                       closer_desc = description,
                                       parent_closer_term = parent_name)
terms_closer <- terms_closer |>
  left_join(terms_closer, by = c("parent_closer_term" = "closer_term"), suffix = c("", "_parent")) |>
  select(-parent_closer_term_parent)

terms_bib <- terms_bib |> select(bib_term = name,
                                 bib_title = title,
                                 bib_desc = description)

projects <- projects |> filter(publish == 1) |> arrange(display_order)

tables <- tables |> filter(publish == 1) |>
  inner_join(select(projects, project_name, project_display_order = display_order), by = "project_name") |>
  arrange(project_display_order, project_name, display_order, table_name)
# remove projects with no tables
projects <- projects |> semi_join(tables, by = "project_name")



```


# Introduction

This is the development version of the BiB data dictionary.

```{r echo=FALSE}

dl_types <- c("All tables", "All variables")
dl_csvs <- c("all_tables.csv", "all_variables.csv")

make_download_table(dl_types, dl_csvs)

```



